//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boxes
    {
        public int id { get; set; }
        public string nameBox { get; set; }
        public Nullable<int> idManufacture { get; set; }
        public Nullable<int> idForm { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual FormFactorMB FormFactorMB { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Powers Powers { get; set; }
    }
}
