//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBoards
    {
        public int id { get; set; }
        public Nullable<int> idManufacture { get; set; }
        public string nameMB { get; set; }
        public Nullable<int> socketMB { get; set; }
        public Nullable<int> typeRam { get; set; }
        public Nullable<int> maxFreq { get; set; }
        public Nullable<int> slotsBus { get; set; }
        public Nullable<int> FFMB { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual FormFactorMB FormFactorMB { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual RamType RamType { get; set; }
        public virtual slotBus slotBus { get; set; }
        public virtual Sockets Sockets { get; set; }
    }
}
