//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersM
    {
        public int idOrder { get; set; }
        public int numberParts { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
        public string namePart { get; set; }
        public int idManufacture { get; set; }
        public bool Status { get; set; }
        public decimal Price { get; set; }
        public string nameTable { get; set; }
        public string Manager { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
