//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities1 : DbContext
    {
        public DiplomEntities1()
            : base("name=DiplomEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIs> APIs { get; set; }
        public virtual DbSet<AudioCards> AudioCards { get; set; }
        public virtual DbSet<Boxes> Boxes { get; set; }
        public virtual DbSet<Cpus> Cpus { get; set; }
        public virtual DbSet<FormFactorMB> FormFactorMB { get; set; }
        public virtual DbSet<HDDs> HDDs { get; set; }
        public virtual DbSet<HDDType> HDDType { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<MotherBoards> MotherBoards { get; set; }
        public virtual DbSet<OrderS> OrderS { get; set; }
        public virtual DbSet<OrdersM> OrdersM { get; set; }
        public virtual DbSet<partsFreq> partsFreq { get; set; }
        public virtual DbSet<Powers> Powers { get; set; }
        public virtual DbSet<Rams> Rams { get; set; }
        public virtual DbSet<RamType> RamType { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<slotBus> slotBus { get; set; }
        public virtual DbSet<Sockets> Sockets { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VideoCards> VideoCards { get; set; }
    }
}
