//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoCards
    {
        public int id { get; set; }
        public string NameVideo { get; set; }
        public Nullable<int> idManufacture { get; set; }
        public Nullable<int> TypeMem { get; set; }
        public Nullable<int> Bus { get; set; }
        public Nullable<int> DirectX { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual APIs APIs { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual RamType RamType { get; set; }
        public virtual slotBus slotBus { get; set; }
    }
}
